version: '3.9'

services:

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5070:80"

  db-dev-1:
    image: postgres:14.5
    container_name: db-dev-1
    command: postgres -c 'max_connections=500'
    ports:
      - "7071:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1

# jdbc:postgresql://localhost:7071/db1?user=user1&password=password1

# sudo docker compose -f db-compose.yml down
# sudo docker compose -f db-compose.yml up -d
